name: Build Project

on:
  workflow_dispatch:   # Manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages and Build Project
      shell: pwsh
      run: |
        $projectFile = Get-ChildItem -Recurse -Filter "*.csproj" | Select-Object -First 1 -ExpandProperty FullName
        $solutionDir = Split-Path $projectFile -Parent

        Write-Host "Restoring NuGet packages..."
        nuget restore $projectFile -SolutionDirectory $solutionDir

        Write-Host "Building project..."
        msbuild $projectFile /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath="${{ github.workspace }}\publish\"

    - name: Build Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: installer.iss

    - name: Debug Installer
      shell: pwsh
      run: Get-ChildItem -Recurse -Filter OptimizerSetup.exe
